### ISSUE TITLE
Duplicate instance with di.As

### ISSUE THREAD

**Issue by gfyrag** [goava/di#23]
Hello
Here the the test case : 
```
package main

import (
	"fmt"
	"github.com/goava/di"
)

type I interface{}

type A struct {}
type B struct {}

func main() {
	c, err := di.New()
	if err != nil {
		panic(err)
	}
	c.Provide(func() I {
		return A{}
	}, di.As(new(I)))
	c.Provide(func() I {
		return B{}
	}, di.As(new(I)))

	is := make([]I, 0)
	err = c.Resolve(&is)
	if err != nil {
		panic(err)
	}
	fmt.Println("Found ", len(is), " instances") 
}
```

This test display "Found 4 instances".

```
package main

import (
	"fmt"
	"github.com/goava/di"
)

type I interface{}

type A struct {}
type B struct {}

func main() {
	c, err := di.New()
	if err != nil {
		panic(err)
	}
	c.Provide(func() interface{} {
		return A{}
	}, di.As(new(I)))
	c.Provide(func() interface{} {
		return B{}
	}, di.As(new(I)))

	is := make([]I, 0)
	err = c.Resolve(&is)
	if err != nil {
		panic(err)
	}
	fmt.Println("Found ", len(is), " instances")
}
```

This test display "Found 2 instances"

The bug, if it is, occurs if constructor functions return a type which match those provided in di.As()

**Comment by justplesh** [comment]
Hi! Thank's for the issue.
There is a couple of points, need to be mentioned.
1. Go-way is to [accept interfaces, return structs](https://twitter.com/davecheney/status/942596109406322688?s=20). So you do not need to return the interface from a constructor function.
2. You do not need to specify `di.As(new(I))` if the constructor returns `I` type by himself. If you will remove `di.As()` calls in the first example - you will see `len(is) = 2`.
3. We will handle such a case in the nearest future, but previous points will help you to fix this issue.

**Comment by gfyrag** [comment]
Hello.
For the point 1, yes it is, in my code, i used unexported struct, so i use the interface instead of change the code, just for the test.
This is not problematic for my usage, i just wanted to report the behavior.
