### ISSUE TITLE
Support the ability to chain containers (to form scopes)

### ISSUE THREAD

**Issue by chirino** [goava/di#33]
It would be nice if you could auto resolve from another container.  Example:

```go
	type Message string
	parent, _ := di.New(di.ProvideValue(Message("Hello from parent")))

	child1, _ := di.New(di.Chain(parent))
	child1.Invoke(func(m Message) { fmt.Println(m) })
```

This would let us have common injection providers in a parent, but still have some child Containers that can inject some variations.  Some DI systems call these DI scopes I think.

**Comment by defval** [comment]
Hi, @chirino 👋  Thanks for your interest!

I have heard about scopes in DI containers and seen several implementations. But in my practice, I have not encountered a real need to separate entities into several containers, especially in Go applications, which are primarily small. I think that scopes are necessary for large codebases with many modules, which components must be isolated from each other. 

Maybe you have a real-life example where this functionality would be helpful? We could discuss it :)

**Comment by chirino** [comment]
We have a case where we support updating the configuration of the server, when the reconfiguration occurs we need to recreate all the services as even the di.Options can change in the child container. 

Right now we are pulling objects out of the parent Container and manually putting it in the new child container.  It  works, but it's not beautiful.

**Comment by defval** [comment]
@chirino Functional released. Thanks a lot!
