### ISSUE TITLE
Add a Application Start and Stop System

### ISSUE THREAD

**Issue by fionera** [goava/di#4]
I am currently using uber-go/fx and I want to switch to DI, but sadly DI is missing a core feature to not run the invokes in compile state, instead having a Start() and Stop() function to kick off the Invokes and run until a control signal got sent, like CTRL+C.

```go
	container := di.New(
// options
	)

	startCtx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	if err := container.Start(startCtx); err != nil {
		log.Fatal(err)
	}

       <- container.Done()

	stopCtx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	if err := container.Stop(stopCtx); err != nil {
		log.Fatal(err)
	}
```
or less verbose if someone doesnt need full controll over the start and stop system

```go
	container := di.New(
// options
	)

         container.Run()
```

**Comment by defval** [comment]
Hi @fionera! Thanks for your interest!

Fx is positioned as a framework. And di is just a container. The container's responsibilities are building the dependency graph, instantiate types, and invoking functions with these types. Control the application lifecycle is not part of these responsibilities.

At the same time, I try to build a composable system of reusable bundles for microservices development in an organization. And the functionality you want will be [here](https://github.com/goava/slice). But I'm just getting started. Feel free to introduce your ideas and features :)

**Comment by defval** [comment]
In the [tutorial](https://github.com/goava/di/blob/master/_tutorial/main.go#L60), you can see how I manage the lifecycle through a standard context, which will be canceled when the signal is received.

**Comment by koolay** [comment]
@fionera 
Hi, why you switch fx to di?

**Comment by defval** [comment]
@koolay Hi!

I can say for myself that after using FX for about a year in production, I encountered some problems that I tried to solve. I understand that Uber is a big company that can not do breaking changes in their libraries. 

Relative to dependency injection:

The main point is associating interface with implementation. `dig.As()` could solve this problem, but the feature [was not released](https://github.com/uber-go/dig/pull/235).

Second is the use of tags for grouping. It was inconvenient for me. Grouping by interfaces looks more explicit. Also, groups in `dig` forced to use `dig.In` and `dig.Out`. It creates more complexity.

In third, lack of clean up.

As for framework, I use a different approach to grouping functionality, but this is a whole other story =)

**Comment by fionera** [comment]
> The main point is associating interface with implementation. `dig.As()` could solve this problem, but the feature [was not released](https://github.com/uber-go/dig/pull/235).

Thats the exact reason why I want to switch to di. I already patched stuff into dig/fx since I needed/wanted them and it is far too verbose.

The reason why I would like to see a Lifecycle and StartStop System like fx in here, which could be made as a wrapping structure to the container, is that I have tens of Invokes that are in the modules of my App. I have to call the init for the db etc and I dont want to have to do this manually...

**Comment by defval** [comment]
@fionera 

You can group functional with `di.Options()` and use `di.Invoke()` option for initialization. On the compile stage invokes will be called:

```go
var Database = di.Options(
	di.Provide(NewDatabase),
	di.Invoke(InitDatabase),
)

var Consul = di.Options(
	di.Provide(NewConsulClient),
	di.Invoke(RegisterInConsul),
)

func main() {
	c, err := di.New(
		Database,
		Consul,
	)
	if err != nil {
		// may database init failed or consul registration failed
	}
	// ...
}
```

Can this help?

**Comment by defval** [comment]
Start/Stop will not be added to the container.
